
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pktqrhqmcavldokgftho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdHFyaHFtY2F2bGRva2dmdGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTczNDQsImV4cCI6MjA2NTc5MzM0NH0.jrRAdyYVX0zRFdX1VmrsN558V6gqcgGWwg4inXrVWi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
